

Psychology students often complain about research methods courses. Psych programs make students do a lot of research methods and yet, when they get to Honours and are running their own project, students are often unprepared for the realities of dealing with real data. 

Research methods courses largely focus on teaching students how to design experiments and do inferential analysis. Students learn a lot about how to run and interpret statistical tests, but often very little about the process of getting real data ready for analysis. The toy datasets used in these courses are clean and tidy, seldom violate assumptions or contain errors and almost remove the need to plot. For Psych students, data visualisation is often an after thought. 

This is not your fault. Research methods lecturers and research supervisors just teach you what they know. But if you want your thesis to stand out of your marker's pile, investing some time in plotting your data will pay off. 


# why plot your data? 


## check your data

- summary statistics can hide wildly different distributions 
- errors (impossible values, coding issues) become visible
- you can see the shape (skew, outliers, bimodality, ceiling/floor effects)

## tell your story

- a good figure makes your effect obvious, it is easier for your marker to digest than a table, or summary stats in the text
- a figure that presents your findings transparently will make your thesis stand out in your marker's pile


This resource is designed to walk you through the process of making plots that check your data for errors and produce plots that tell your story. You can choose to use the open source GUI-based software JAMOVI, in combinatinon with the vijPlots module, or to use the `ggplot` package in RStudio. 





```

